/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

        
import com.alee.laf.WebLookAndFeel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author HoussemEddine
 */
public class Frame_Authentification extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Authentification
     */
    public Frame_Authentification() {
        try {
            UIManager.setLookAndFeel(new WebLookAndFeel());
            initComponents();
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Frame_Authentification.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JTabbedPane();
        Panel_Admin = new javax.swing.JPanel();
        tfLogin_Admin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnConnect_Admin = new javax.swing.JButton();
        pfPwd_Admin = new javax.swing.JPasswordField();
        Panel_Ph = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        tfLogin_Ph = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        pfPwd_Ph = new javax.swing.JPasswordField();
        btnConnect_Ph = new javax.swing.JButton();
        lblInscrit_Ph = new javax.swing.JLabel();
        Panel_Clt = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        tfLogin_Clt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        pfPwd_Clt = new javax.swing.JPasswordField();
        btnConnect_Clt = new javax.swing.JButton();
        lblInscrit_Clt = new javax.swing.JLabel();
        FormulairePh = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        btnSuiv = new javax.swing.JButton();
        FormulairePh_Suiv = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        btnInscrit_Ph = new javax.swing.JButton();
        btnPreced = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        FormulaireClt = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        btnInscrit_Clt = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setName("S'authentifier"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        Panel_Admin.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                Panel_AdminComponentShown(evt);
            }
        });

        jLabel8.setText("Login :");

        jLabel9.setText("Mot de Passe :");

        btnConnect_Admin.setText("Se Connecter");

        javax.swing.GroupLayout Panel_AdminLayout = new javax.swing.GroupLayout(Panel_Admin);
        Panel_Admin.setLayout(Panel_AdminLayout);
        Panel_AdminLayout.setHorizontalGroup(
            Panel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_AdminLayout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(Panel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(Panel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConnect_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(tfLogin_Admin)
                    .addComponent(pfPwd_Admin))
                .addGap(51, 51, 51))
        );
        Panel_AdminLayout.setVerticalGroup(
            Panel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_AdminLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(Panel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLogin_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(pfPwd_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConnect_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        Menu.addTab("Espace Administrateur", Panel_Admin);

        Panel_Ph.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                Panel_PhComponentShown(evt);
            }
        });

        jLabel22.setText("Login :");

        jLabel23.setText("Mot de Passe :");

        btnConnect_Ph.setText("Se Connecter");

        lblInscrit_Ph.setText("S'inscrire");
        lblInscrit_Ph.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInscrit_PhMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_PhLayout = new javax.swing.GroupLayout(Panel_Ph);
        Panel_Ph.setLayout(Panel_PhLayout);
        Panel_PhLayout.setHorizontalGroup(
            Panel_PhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_PhLayout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(Panel_PhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(Panel_PhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_PhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnConnect_Ph, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addComponent(tfLogin_Ph)
                        .addComponent(pfPwd_Ph, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addComponent(lblInscrit_Ph, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );
        Panel_PhLayout.setVerticalGroup(
            Panel_PhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_PhLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(Panel_PhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLogin_Ph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_PhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(pfPwd_Ph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConnect_Ph, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInscrit_Ph)
                .addGap(17, 17, 17))
        );

        Menu.addTab("Espace Pharmacien", Panel_Ph);

        Panel_Clt.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                Panel_CltComponentShown(evt);
            }
        });

        jLabel20.setText("Login :");

        jLabel21.setText("Mot de Passe :");

        btnConnect_Clt.setText("Se Connecter");

        lblInscrit_Clt.setText("S'inscrire");
        lblInscrit_Clt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInscrit_CltMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_CltLayout = new javax.swing.GroupLayout(Panel_Clt);
        Panel_Clt.setLayout(Panel_CltLayout);
        Panel_CltLayout.setHorizontalGroup(
            Panel_CltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_CltLayout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(Panel_CltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(Panel_CltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInscrit_Clt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_CltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnConnect_Clt, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addComponent(tfLogin_Clt)
                        .addComponent(pfPwd_Clt, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                .addGap(51, 51, 51))
        );
        Panel_CltLayout.setVerticalGroup(
            Panel_CltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_CltLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(Panel_CltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLogin_Clt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_CltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(pfPwd_Clt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConnect_Clt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInscrit_Clt)
                .addGap(17, 17, 17))
        );

        Menu.addTab("Espace Client", Panel_Clt);

        getContentPane().add(Menu);
        Menu.setBounds(10, 140, 430, 280);

        FormulairePh.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fomulaire", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        FormulairePh.setLayout(null);

        jLabel1.setText("Nom :");
        FormulairePh.add(jLabel1);
        jLabel1.setBounds(35, 34, 28, 14);

        jLabel2.setText("Prénom :");
        FormulairePh.add(jLabel2);
        jLabel2.setBounds(35, 65, 43, 14);

        jLabel3.setText("CIN :");
        FormulairePh.add(jLabel3);
        jLabel3.setBounds(35, 96, 25, 14);

        jLabel4.setText("Référence :");
        FormulairePh.add(jLabel4);
        jLabel4.setBounds(35, 127, 57, 14);

        jLabel5.setText("E-Mail :");
        FormulairePh.add(jLabel5);
        jLabel5.setBounds(35, 158, 35, 14);

        jLabel6.setText("Diplome :");
        FormulairePh.add(jLabel6);
        jLabel6.setBounds(35, 189, 44, 14);

        jLabel7.setText("Date de Naissance :");
        FormulairePh.add(jLabel7);
        jLabel7.setBounds(35, 217, 96, 14);
        FormulairePh.add(jDateChooser1);
        jDateChooser1.setBounds(164, 211, 150, 20);

        jTextField7.setText("jTextField7");
        FormulairePh.add(jTextField7);
        jTextField7.setBounds(164, 31, 150, 20);

        jTextField8.setText("jTextField7");
        FormulairePh.add(jTextField8);
        jTextField8.setBounds(164, 242, 150, 20);

        jTextField9.setText("jTextField7");
        FormulairePh.add(jTextField9);
        jTextField9.setBounds(164, 62, 150, 20);

        jTextField10.setText("jTextField7");
        FormulairePh.add(jTextField10);
        jTextField10.setBounds(164, 93, 150, 20);

        jTextField11.setText("jTextField7");
        FormulairePh.add(jTextField11);
        jTextField11.setBounds(164, 186, 150, 20);

        jTextField12.setText("jTextField7");
        FormulairePh.add(jTextField12);
        jTextField12.setBounds(164, 124, 150, 20);

        jTextField13.setText("jTextField7");
        FormulairePh.add(jTextField13);
        jTextField13.setBounds(164, 155, 150, 20);

        jLabel16.setText("Numéro du Pharmacie :");
        FormulairePh.add(jLabel16);
        jLabel16.setBounds(35, 245, 111, 14);

        jLabel17.setText("Code Postal :");
        FormulairePh.add(jLabel17);
        jLabel17.setBounds(35, 276, 64, 14);

        jLabel18.setText("Adresse :");
        FormulairePh.add(jLabel18);
        jLabel18.setBounds(35, 307, 46, 14);

        jTextField14.setText("jTextField14");
        FormulairePh.add(jTextField14);
        jTextField14.setBounds(164, 273, 150, 20);

        jTextField15.setText("jTextField15");
        FormulairePh.add(jTextField15);
        jTextField15.setBounds(164, 304, 150, 20);

        btnSuiv.setText("Suivant");
        btnSuiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivActionPerformed(evt);
            }
        });
        FormulairePh.add(btnSuiv);
        btnSuiv.setBounds(243, 349, 81, 23);

        getContentPane().add(FormulairePh);
        FormulairePh.setBounds(450, 30, 340, 390);

        FormulairePh_Suiv.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fomulaire", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        FormulairePh_Suiv.setLayout(null);

        jLabel14.setText("Identifiant :");
        FormulairePh_Suiv.add(jLabel14);
        jLabel14.setBounds(35, 34, 57, 14);

        jLabel15.setText("Mot de Passe :");
        FormulairePh_Suiv.add(jLabel15);
        jLabel15.setBounds(35, 65, 71, 14);

        jLabel19.setText("Confirmer votre Mot de Passe :");
        FormulairePh_Suiv.add(jLabel19);
        jLabel19.setBounds(35, 96, 150, 14);

        jTextField16.setText("jTextField7");
        FormulairePh_Suiv.add(jTextField16);
        jTextField16.setBounds(218, 31, 98, 20);

        btnInscrit_Ph.setText("S'inscrire");
        btnInscrit_Ph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscrit_PhActionPerformed(evt);
            }
        });
        FormulairePh_Suiv.add(btnInscrit_Ph);
        btnInscrit_Ph.setBounds(210, 220, 116, 32);

        btnPreced.setText("Précedent");
        btnPreced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecedActionPerformed(evt);
            }
        });
        FormulairePh_Suiv.add(btnPreced);
        btnPreced.setBounds(10, 230, 99, 23);

        jPasswordField1.setText("jPasswordField1");
        FormulairePh_Suiv.add(jPasswordField1);
        jPasswordField1.setBounds(218, 62, 98, 20);

        jPasswordField2.setText("jPasswordField2");
        FormulairePh_Suiv.add(jPasswordField2);
        jPasswordField2.setBounds(218, 93, 98, 20);

        getContentPane().add(FormulairePh_Suiv);
        FormulairePh_Suiv.setBounds(450, 160, 340, 260);

        FormulaireClt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fomulaire", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        FormulaireClt.setLayout(null);

        jLabel30.setText("Nom :");
        FormulaireClt.add(jLabel30);
        jLabel30.setBounds(35, 34, 28, 14);

        jLabel31.setText("Prénom :");
        FormulaireClt.add(jLabel31);
        jLabel31.setBounds(35, 65, 43, 14);

        jLabel32.setText("Identifiant :");
        FormulaireClt.add(jLabel32);
        jLabel32.setBounds(35, 96, 57, 14);

        jLabel33.setText("Mot de Passe :");
        FormulaireClt.add(jLabel33);
        jLabel33.setBounds(35, 127, 71, 14);

        jLabel34.setText("Retaper Mot de Passe :");
        FormulaireClt.add(jLabel34);
        jLabel34.setBounds(35, 158, 113, 14);

        jLabel35.setText("E-Mail :");
        FormulaireClt.add(jLabel35);
        jLabel35.setBounds(35, 189, 35, 14);

        jLabel36.setText("Région :");
        FormulaireClt.add(jLabel36);
        jLabel36.setBounds(35, 217, 40, 14);

        jTextField26.setText("jTextField7");
        FormulaireClt.add(jTextField26);
        jTextField26.setBounds(166, 31, 150, 20);

        jTextField27.setText("jTextField7");
        FormulaireClt.add(jTextField27);
        jTextField27.setBounds(166, 242, 150, 20);

        jTextField28.setText("jTextField7");
        FormulaireClt.add(jTextField28);
        jTextField28.setBounds(166, 62, 150, 20);

        jTextField29.setText("jTextField7");
        FormulaireClt.add(jTextField29);
        jTextField29.setBounds(166, 93, 150, 20);

        jTextField30.setText("jTextField7");
        FormulaireClt.add(jTextField30);
        jTextField30.setBounds(166, 186, 150, 20);

        jTextField31.setText("jTextField7");
        FormulaireClt.add(jTextField31);
        jTextField31.setBounds(166, 124, 150, 20);

        jTextField32.setText("jTextField7");
        FormulaireClt.add(jTextField32);
        jTextField32.setBounds(166, 155, 150, 20);

        jLabel37.setText("Code Postal :");
        FormulaireClt.add(jLabel37);
        jLabel37.setBounds(35, 245, 64, 14);

        jLabel38.setText("Adresse :");
        FormulaireClt.add(jLabel38);
        jLabel38.setBounds(35, 276, 46, 14);

        jTextField33.setText("jTextField14");
        FormulaireClt.add(jTextField33);
        jTextField33.setBounds(166, 273, 150, 20);

        btnInscrit_Clt.setText("S'inscrire");
        btnInscrit_Clt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscrit_CltActionPerformed(evt);
            }
        });
        FormulaireClt.add(btnInscrit_Clt);
        btnInscrit_Clt.setBounds(199, 336, 117, 36);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        FormulaireClt.add(jComboBox1);
        jComboBox1.setBounds(166, 214, 150, 20);

        getContentPane().add(FormulaireClt);
        FormulaireClt.setBounds(450, 30, 340, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setSize(464, 466);
        FormulairePh_Suiv.setVisible(false);
        FormulairePh.setVisible(false);
        FormulaireClt.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void lblInscrit_PhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInscrit_PhMouseClicked
        this.setSize(815, 466);
        FormulairePh.setVisible(true);
    }//GEN-LAST:event_lblInscrit_PhMouseClicked

    private void btnPrecedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecedActionPerformed
        FormulairePh_Suiv.setVisible(false);
        FormulairePh.setVisible(true);
    }//GEN-LAST:event_btnPrecedActionPerformed

    private void btnInscrit_PhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscrit_PhActionPerformed
        this.setSize(464, 466);
        FormulairePh_Suiv.setVisible(false);
    }//GEN-LAST:event_btnInscrit_PhActionPerformed

    private void btnSuivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivActionPerformed
        FormulairePh.setVisible(false);
        FormulairePh_Suiv.setVisible(true);
    }//GEN-LAST:event_btnSuivActionPerformed

    private void btnInscrit_CltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscrit_CltActionPerformed
        this.setSize(464, 466);
        FormulaireClt.setVisible(false);
    }//GEN-LAST:event_btnInscrit_CltActionPerformed

    private void lblInscrit_CltMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInscrit_CltMouseClicked
        this.setSize(815, 466);
        FormulaireClt.setVisible(true);
    }//GEN-LAST:event_lblInscrit_CltMouseClicked

    private void Panel_AdminComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Panel_AdminComponentShown
        this.setSize(464, 466);
        FormulairePh_Suiv.setVisible(false);
        FormulairePh.setVisible(false);
        FormulaireClt.setVisible(false);
    }//GEN-LAST:event_Panel_AdminComponentShown

    private void Panel_PhComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Panel_PhComponentShown
        this.setSize(464, 466);
        FormulairePh_Suiv.setVisible(false);
        FormulairePh.setVisible(false);
        FormulaireClt.setVisible(false);
    }//GEN-LAST:event_Panel_PhComponentShown

    private void Panel_CltComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Panel_CltComponentShown
        this.setSize(464, 466);
        FormulairePh_Suiv.setVisible(false);
        FormulairePh.setVisible(false);
        FormulaireClt.setVisible(false);
    }//GEN-LAST:event_Panel_CltComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Authentification().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FormulaireClt;
    private javax.swing.JPanel FormulairePh;
    private javax.swing.JPanel FormulairePh_Suiv;
    private javax.swing.JTabbedPane Menu;
    private javax.swing.JPanel Panel_Admin;
    private javax.swing.JPanel Panel_Clt;
    private javax.swing.JPanel Panel_Ph;
    private javax.swing.JButton btnConnect_Admin;
    private javax.swing.JButton btnConnect_Clt;
    private javax.swing.JButton btnConnect_Ph;
    private javax.swing.JButton btnInscrit_Clt;
    private javax.swing.JButton btnInscrit_Ph;
    private javax.swing.JButton btnPreced;
    private javax.swing.JButton btnSuiv;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblInscrit_Clt;
    private javax.swing.JLabel lblInscrit_Ph;
    private javax.swing.JPasswordField pfPwd_Admin;
    private javax.swing.JPasswordField pfPwd_Clt;
    private javax.swing.JPasswordField pfPwd_Ph;
    private javax.swing.JTextField tfLogin_Admin;
    private javax.swing.JTextField tfLogin_Clt;
    private javax.swing.JTextField tfLogin_Ph;
    // End of variables declaration//GEN-END:variables
}
